### PR TITLE
Typescript rewrite, v1.0.0-beta1

### PR DESCRIPTION
**Pull request by AlexanderArvidsson**

### CODE REVIEW

**Comment by ryanking1809** [comment]
Ok, you just had one typo but otherwise it looks like it works!

My only issue is when it is built, an `eval` function appears in the code. I can't figure out where it comes from - but maybe it's fine?

**Comment by AlexanderArvidsson** [comment]
@ryanking1809 It comes from `file-type` dependency that Arango depends on. Good catch with that typo, I forgot to change it back when I was checking if `create` method had an upsert option, which it didn't.
Good to have a prettier config, too. I was gonna add it but you were faster :)

**Comment by AlexanderArvidsson** [comment]
@ryanking1809 One thing that I am wondering about is the type of the serialize & deserialize argument & return value. It might become problematic for people writing their own serialize functions?

**Comment by ryanking1809** [comment]
Yeah that’s true, you can’t really guarantee much. Serialise will accept
the session data and deserialise will return session data. But there isn’t
much you can guarantee about what’s in the session data anyway.

**Comment by AlexanderArvidsson** [comment]
@ryanking1809 I really don't like using `any` and I have ESLint set up to specifically prevent it from letting me use it, but maybe it's necessary here.
We could dive into generics though, Typescript would automatically infer the type of the serialized data (it has to extend ArangoSessionData though). Although, I would need to have a use-case for custom serialized data in order to implement this to begin with. Right now I don't see any reason someone would want to serialize it manually, do you (then again, last time I used (connect-*) libraries or ArangoJS was maybe 10 years ago)?

**Comment by ryanking1809** [comment]
Most of the other libraries use `any` in this case eg. https://github.com/jdesboeufs/connect-mongo/blob/master/src/lib/MongoStore.ts - you could guarantee they're objects at the very least as arango / express-session will be expecting that. 

I imagine the most common use case would be if you had an entire class you didn't want to commit to the database. However, I do think that any use case of serialize could just as easily be implemented externally to the store. You just serialize before modifying the session and deserialize when reading from it. So I think it can be cut without consequence.

**Comment by AlexanderArvidsson** [comment]
@ryanking1809 For the record, I'm gonna leave the rest to you for this MR. I got no time to continue for now :) Feel free to merge it once you feel like it is ready. When you want to publish, let me know, I'll get to it when I have time.

**Comment by ryanking1809** [comment]
No problem, I might fix up serialize/deserialize later in the week and then I think it's good to go.

**Pull request merged**
