### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by ryanking1809**
So I ended up rewriting the whole thing but thought I'd run it by you before merging. 

The sessions now auto delete via arango's `TTL Index` The API has a few breaking changes (see readme: https://github.com/ryanking1809/connect-arango). We could release it as a new version (which I'm fine with), or I could go back and support the old stuff.

You'll have to do a `yarn install` & ` yarn build` before pushing to npm.

**API Changes**

```js
var ArangoStore = require('connect-arango')(session);
```
is now just
```js
var ArangoStore = require('connect-arango');
```
I could add a wrapper to support the old functionality.

**Options**
* `db` (modified) - now accepts an external `aragnojs` database as well as original input
* `stringify` (removed) - I think a user could just add this to `serialize`
* `serialize` / `deserialize` (unchanged)
* `clear_interval` / `ttl` (removed) - functionality is now managed on the database
* `collectionName` (added) - change the collection name
* `autoRemove` (added) - to turn on/off automatic session deletion
* `disableTouch` (added) - to turn off `express-session` updating the session expiry time on touch

### CODE REVIEW

**Comment by AlexanderArvidsson** [comment]
Great work, looks good at a glance for me. I do not have a way of testing it out though, and I would recommend we publish this as a new version.
However, if we are going to publish a major version, I would suggest rewriting this to Typescript and publishing it as a 1.0.0-beta1. It should be very trivial to do if you've worked with Typescript before.
Would you be up to the task to do this?

**Comment by ryanking1809** [comment]
I've never got around to learning typescript, unfortunately. It could be a nice little project to learn but I'm not sure when I'll have the time for it. 

What if we publish this one as `1.0.0-beta1` and I could come back to it when I have time for typescript (or leave it open for someone else to do) - then go for `1.0.0` when we have typescript?

**Comment by AlexanderArvidsson** [comment]
> I've never got around to learning typescript, unfortunately. It could be a nice little project to learn but I'm not sure when I'll have the time for it.
> 
> What if we publish this one as `1.0.0-beta1` and I could come back to it when I have time for typescript (or leave it open for someone else to do) - then go for `1.0.0` when we have typescript?

I think I could rewrite it to typescript. It should only take an hour tops, maybe less. I'll try doing it tomorrow.

**Comment by ryanking1809** [comment]
Great, let me know if you need a hand wrapping your head around something.

**Comment by AlexanderArvidsson** [comment]
I have now finished the rewrite to Typescript. However, since I have no proper Arango environment (and no time to set one up), I have not tested it. Let's continue the discussion in #10.
You should continue work on `v1` branch rather than your fork, since I've added you as contributor already.

I have never used rollup before so please check if I set it up correctly. It does warn about `eval` usage from `file-type` dependency of `arangojs`.

**Pull request closed without merging**
